name: rocketchat
description: Prepare to take off with the ultimate chat platform, experience the next level of team communications
annotations:
  title: 'Rocket.Chat'
type: application
version: 6.1.5
apiVersion: v2
appVersion: 6.1.5
maintainers:
  - email: cloud@rocket.chat
    name: RocketChat
dependencies:
  - name: common
    repository: file://../../../common/2304.0.1
    version: 2304.0.1
  - name: mongodb
    repository: file://charts/mongodb-13.10.2
    version: 13.10.2
    condition: mongodb.enabled
  - name: nats
    repository: file://charts/nats-0.15.1
    version: 0.15.1
    condition: microservices.enabled
home: https://rocket.chat/
icon: https://raw.githubusercontent.com/RocketChat/Rocket.Chat.Artwork/master/Logos/icon.svg
sources:
  - https://github.com/RocketChat/Docker.Official.Image/
keywords:
  - chat
  - communication
  - http
  - web
  - application
  - nodejs
  - javascript
  - meteor
engine: gotpl

